import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { inter } from "./fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Banner from "@/components/Banner";
import { bannerMessages } from "@/lib/banner-messages";

export const metadata: Metadata = {
  title: "Dollar Sine",
  description: "Generated by create next app",
  /* icons: {
    icon: [
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-light.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-dark.png",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  }, */
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bannerObj = bannerMessages[bannerMessages.length - 1];
  const [text, publishDate] = [bannerObj.text, bannerObj.publishDate];
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`bg-[#fff] dark:bg-[#121212] ${inter.className} site-container`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Toaster /> */}
            <div className="page-content flex-col">
              <Banner text={text} publishDate={publishDate} />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
