import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Dollar Sine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#f5f5f5] dark:bg-[#121212] ${inter.className} flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            <div className="grow w-dvw">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
