import { Metadata } from "next";

export function setTitle(
  title: string,
  description: string = "Generated by create next app"
): Metadata {
  return {
    title: `${title} | Dollar Sine`,
    description,
  };
}
