import type { Metadata } from "next";
import { dir } from "i18next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/theme-provider";
// import { bannerMessages } from "@/utils/banner-info";
import { i18nConfig } from "@/i18nConfig";
import "../globals.css";
import { inter } from "../fonts";
import TranslationsProvider from "@/components/ui/translations-provider";
import initTranslations from "../i18n";
import OnboardingBanner from "@/components/OnboardingBanner";
import { Toaster } from "@/components/ui/toaster";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Dollar Sine",
  description: "Generated by create next app",
  /* icons: {
    icon: [
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-light.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-dark.png",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  }, */
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const i18nNamespaces = ["layout", "banner"];

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // const bannerObj = bannerMessages[bannerMessages.length - 1];
  // const [header, text, publishDate, buttonText, buttonHref] = [
  //   bannerObj.header,
  //   bannerObj.text,
  //   bannerObj.publishDate,
  //   bannerObj.buttonText,
  //   bannerObj.buttonHref,
  // ];

  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <ClerkProvider>
      <html lang={locale} dir={dir(locale)} suppressHydrationWarning={true}>
        <body
          className={`site-container bg-dodger-blue-50 dark:bg-[#121212] text-woodsmoke-950 dark:text-woodsmoke-50 ${inter.className}`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TranslationsProvider
              namespaces={i18nNamespaces}
              locale={locale}
              resources={resources}
            >
              <NuqsAdapter>
                <main className="page-content">
                  <OnboardingBanner />
                  {children}
                </main>
              </NuqsAdapter>
              <Toaster />
            </TranslationsProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
