import type { Metadata } from "next";
import { dir } from "i18next";
import { ClerkProvider } from "@clerk/nextjs";
import Banner from "@/components/Banner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { bannerMessages } from "@/utils/banner-info";
import { i18nConfig } from "@/i18nConfig";
import "../globals.css";
import { inter } from "../fonts";
import TranslationsProvider from "@/components/ui/translations-provider";
import initTranslations from "../i18n";
import OnboardingBanner from "@/components/OnboardingBanner";
import VerifyEmailBanner from "@/components/VerifyEmailBanner";
import { Toaster } from "@/components/ui/toaster";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import ActiveUserContextProvider from "@/contexts/active-user-context";

export const metadata: Metadata = {
  title: "Dollar Sine",
  description: "Generated by create next app",
  /* icons: {
    icon: [
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-light.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        rel: "icon",
        type: "image/png",
        url: "../assets/images/favicon-dark.png",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  }, */
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const i18nNamespaces = ["layout", "banner"];

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const bannerObj = bannerMessages[bannerMessages.length - 1];
  const [header, text, publishDate, buttonText, buttonHref] = [
    bannerObj.header,
    bannerObj.text,
    bannerObj.publishDate,
    bannerObj.buttonText,
    bannerObj.buttonHref,
  ];

  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <ClerkProvider>
      <html lang={locale} dir={dir(locale)} suppressHydrationWarning={true}>
        <body
          className={`bg-[#fff] dark:bg-[#121212] ${inter.className} site-container text-woodsmoke-950 dark:text-woodsmoke-50`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TranslationsProvider
              namespaces={i18nNamespaces}
              locale={locale}
              resources={resources}
            >
              <ActiveUserContextProvider>
                <NuqsAdapter>
                  <div className="page-content flex-col">
                    <OnboardingBanner />
                    <VerifyEmailBanner />
                    {/* <Banner
                  header={header}
                  text={text}
                  publishDate={publishDate}
                  buttonText={buttonText}
                  buttonHref={buttonHref}
                /> */}
                    {children}
                  </div>
                </NuqsAdapter>
              </ActiveUserContextProvider>
              <Toaster />
            </TranslationsProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
